[theme]
base="dark"
primaryColor="#2E9CCA"              # Warna utama cerah (aksen biru)
backgroundColor="#25274D"           # Latar utama (biru tua gelap)
secondaryBackgroundColor="#464866"  # Latar sidebar / form
textColor="#F8F7F3"                 # Teks utama terang
font="sans serif"
